{% set version = "4.2.2" %}
{% set name = "pyobjc-framework-Cocoa" %}

package:
  name: pyobjc-framework-cocoa
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 99b33ab038b90e8866e4cb510213f235c3010982fa425d8f34850c45ece30c43

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: true  # [not osx]

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pyobjc-core

test:
  imports:
    - AppKit
    - Cocoa
    - CoreFoundation
    - Foundation
    - PyObjCTools

about:
  home: https://bitbucket.org/ronaldoussoren/pyobjc
  license: MIT
  license_file: LICENSE.txt
  summary: Wrappers for the Cocoa frameworks on Mac OS X

extra:
  recipe-maintainers:
    - jschueller
