{% set version = "7.3" %}
{% set name = "pyobjc-framework-Cocoa" %}

package:
  name: pyobjc-framework-cocoa
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b18d05e7a795a3455ad191c3e43d6bfa673c2a4fd480bb1ccf57191051b80b7e
  patches:
    - 0001-do-not-add-Werror.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [(not osx) or py2k]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pyobjc-core >={{ version }}

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - AppKit
    - Cocoa
    - CoreFoundation
    - Foundation
    - PyObjCTools

about:
  home: https://bitbucket.org/ronaldoussoren/pyobjc
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: Wrappers for the Cocoa frameworks on Mac OS X
  dev_url: https://github.com/ronaldoussoren/pyobjc/tree/master/pyobjc-framework-Cocoa
  doc_url: https://github.com/ronaldoussoren/pyobjc/blob/master/pyobjc-framework-Cocoa/README.txt

extra:
  recipe-maintainers:
    - jschueller
