# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "g2mgMVaHmz1VZhnJUmD4lZ8YOlJAWiHiz6KH0tSVd0YLZxW102fDz+jcZ9bOA5TU//a1fIjiyob8ETG4b71UVn5D4Yf0p+Zb9ckYNmw1Sg4YWJtrFeriTNqRoaFuxF18O3kP3E4bokLNLqRJT5dkMe4qdb6g0oBFlzl4L2mIeG2HQJQ8/h30U8DUp1IZfKD/SZBYmuLuNZDO8e7vuotSQ0AcYm8wIQGYxT07IBR6eV1Nnk6ecWa8NBobrCi3Rm7kVbcOiTvtYWiy39EFZ5pv/Scj+gi4KDz39CPSpjlkI9d/30ex6+Rc8p4O8jJNrX8KevbZyT3bk0XHsCVkgRLfkH289YHt3nIFXYMzglQ382aKJNw5+75fayjf13ehoObD7jNzeNePeYjtHLfz64gHtrZTsWIN5RbnbulcE9ExVDHZRVvUWTU3fAdj/66CJBLynvCzn28EP5XpmQbppTYk9hYq7dPN1qgWHagewCFEZJNfqe0Iuldy+x1gFCTDdo9mR+GCR5Nt2bgadzAISdh+6ClWQstN7JtcaTxi0Nxk3WmHM2wovu+5QDF15w1qRyRbGgjhZYyBMZ+d+DLIe3FYRTYntJwmhQ/E1eSvh6yLYgS+hv19A3BRzjrspc6tYBPovDorXWsqHYOtlx2GUAEvHyFl6NX5VwU9r81T5WckXx0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
