travis:
  secure:
    BINSTAR_TOKEN: g2mgMVaHmz1VZhnJUmD4lZ8YOlJAWiHiz6KH0tSVd0YLZxW102fDz+jcZ9bOA5TU//a1fIjiyob8ETG4b71UVn5D4Yf0p+Zb9ckYNmw1Sg4YWJtrFeriTNqRoaFuxF18O3kP3E4bokLNLqRJT5dkMe4qdb6g0oBFlzl4L2mIeG2HQJQ8/h30U8DUp1IZfKD/SZBYmuLuNZDO8e7vuotSQ0AcYm8wIQGYxT07IBR6eV1Nnk6ecWa8NBobrCi3Rm7kVbcOiTvtYWiy39EFZ5pv/Scj+gi4KDz39CPSpjlkI9d/30ex6+Rc8p4O8jJNrX8KevbZyT3bk0XHsCVkgRLfkH289YHt3nIFXYMzglQ382aKJNw5+75fayjf13ehoObD7jNzeNePeYjtHLfz64gHtrZTsWIN5RbnbulcE9ExVDHZRVvUWTU3fAdj/66CJBLynvCzn28EP5XpmQbppTYk9hYq7dPN1qgWHagewCFEZJNfqe0Iuldy+x1gFCTDdo9mR+GCR5Nt2bgadzAISdh+6ClWQstN7JtcaTxi0Nxk3WmHM2wovu+5QDF15w1qRyRbGgjhZYyBMZ+d+DLIe3FYRTYntJwmhQ/E1eSvh6yLYgS+hv19A3BRzjrspc6tYBPovDorXWsqHYOtlx2GUAEvHyFl6NX5VwU9r81T5WckXx0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
