travis:
  secure:
    BINSTAR_TOKEN: d7FtSijA74RC7PE7fGcvMvgV8Y7S07CrGLp2JcwhjZs7Al0pkYHArUXKDXtE9SroGCmtZ1zEYmhPRqAdH6vULK00Si0oU9iW+5aUyafyfpF86eV3Ld4HWCO1310fW0mH15ngvn54CdAFRlm9cBp3XaUC26M5Jz+1qoYmDBDmh9x8scPl6ka9NS6jgia1XfakHw/oF3ct8/NXBMAT/lfYfKJQ1eu3tsfGiAFFT2cppUOGYWVXQOIXMp2/lkomQDx3df3u6rttaTulcOE/1Ev3l5oD7Mhb+esBdVB26jfHdYJT9jA0kQXQFgmcOcv7BeQ7T7QpBFQMNV68Y8SoQgf7qc/RnGxt11hA4PfZLU5vvJ+UBjcWEl+28BUA2BolVAWvm/6Jfmv6EPAGwsyMolwL5ceMxaldLZbCaXPJmkAr4k4Gqt8iHVqqFem35KkdJF6r5S4NE+RXothebcgn+7+tv08+8kKG2+HGLHEuO+UiWUWGmuYoezOIvjv08/dXmjPD9GCmN9JmNcS76giXHG3rd47ufFp2RbKulStPsXMh8tFT1R4F3a14hHtVvaRNQkyJTyn3Tsxb2iRO5cu3dAonkYPpjcb7UZD3R4YZn6g3RoaoyJIM/n0oYoDjn5JajAAQNyy1Rnp31o8pvO07Um0QQzkVPVTcPPwBcarldGJjgn0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
